function createGroupConv(X1, yd1, yd2, Y1, Y2, Y3, Y4)
%CREATEFIGURE(X1, YD1, YD2, H1, Y1, Y2, Y3, Y4)
%  X1:  vector of x data
%  YD1:  vector of y data
%  YD2:  vector of y data
%  Y1:  vector of y data
%  Y2:  vector of y data
%  Y3:  vector of y data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 17-Jan-2016 17:03:54

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YTick',[2e-06 3e-06],...
    'YColor',[0 0.447 0.741],...
    'FontWeight','bold',...
    'FontSize',14,...
    'Position',[0.129136400322841 0.583837209302326 0.775863599677159 0.341162790697675]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 100]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[2e-06 3e-06]);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,yd1,'Parent',axes1,'DisplayName','yd2');

% Create axes
axes2 = axes('Parent',figure1,'HitTest','off','Color','none',...
    'YTick',[0.5 1],...
    'YColor',[0.85 0.325 0.098],...
    'YAxisLocation','right',...
    'Position',[0.129136400322841 0.583837209302326 0.775863599677159 0.341162790697675]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 100]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes2,[0 1]);
hold(axes2,'on');

% Create plot
plot(X1,yd2,'Parent',axes2,'DisplayName','yd1');

% Create axes
axes3 = axes('Parent',figure1,'YTick',[2e-06 2.5e-06 3e-06],...
    'YColor',[0 0.447 0.741],...
    'Position',[0.13 0.11 0.334659090909091 0.341162790697674]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 100]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[2e-06 3e-06]);
box(axes3,'on');
hold(axes3,'on');

% Create plot
plot(X1,Y1,'Parent',axes3);

% Create axes
axes4 = axes('Parent',figure1,...
    'YTick',[9.905e-05 9.91e-05 9.915e-05 9.92e-05],...
    'YColor',[0 0.447 0.741],...
    'Position',[0.570340909090909 0.11 0.334659090909091 0.341162790697674]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes4,[0 100]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes4,[9.905e-05 9.92e-05]);
box(axes4,'on');
hold(axes4,'on');

% Create plot
plot(X1,Y2,'Parent',axes4);

% Create axes
axes5 = axes('Parent',figure1,'HitTest','off','Color','none',...
    'YTick',[0.5 0.6 0.7],...
    'YColor',[0.85 0.325 0.098],...
    'YAxisLocation','right',...
    'Position',[0.13 0.11 0.334659090909091 0.341162790697674]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes5,[0 100]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes5,[0 1]);
hold(axes5,'on');

% Create plot
plot(X1,Y3,'Parent',axes5);

% Create axes
axes6 = axes('Parent',figure1,'HitTest','off','Color','none',...
    'YTick',[0 0.1 0.2 0.3],...
    'YColor',[0.85 0.325 0.098],...
    'YAxisLocation','right',...
    'Position',[0.570340909090909 0.11 0.334659090909091 0.341162790697674]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes6,[0 100]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes6,[0 1]);
hold(axes6,'on');

% Create plot
plot(X1,Y4,'Parent',axes6);

