function paperErrorPlots(XMatrix1, YMatrix1) %EMatrix1)
%CREATEFIGURE(XMATRIX1, YMATRIX1, EMATRIX1)
%  XMATRIX1:  errorbar x matrix
%  YMATRIX1:  errorbar y matrix
%  EMATRIX1:  errorbar e matrix

%  Auto-generated by MATLAB on 15-Jan-2016 17:19:45

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'XTickLabel',{'0','10','30','50','70','90'},...
    'XTick',[1 2 3 4 5 6],...
    'FontSize',14,...
    'Position',[0.241909554482019 0.146988795518207 0.533923778851315 0.781932773109244]);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 7]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.2 1]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple error bars using matrix input to errorbar
errorbar1 = plot(XMatrix1,YMatrix1,'MarkerSize',8,...
    'Marker','diamond',...
    'LineWidth',2);
set(errorbar1(1),'DisplayName','GPVC');
set(errorbar1(2),'DisplayName','PVC');
set(errorbar1(3),'DisplayName','CentroidSc');
set(errorbar1(4),'DisplayName','PairwiseSc');

% Create xlabel
xlabel('PER (%)','FontSize',15.4);

% Create ylabel
ylabel('NMI','FontSize',15.4);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.667222223563327 0.71813725950379 0.0916666653255622 0.170751629385099]);

